### ISSUE TITLE
Support .NET Standard 1.3+

### ISSUE THREAD

**Issue by sergiorykov** [logzio/logzio-dotnet#14]
Actually _there is no way to log to logz.io from .NET_ as use **official** package. 

[It seems](https://github.com/logzio/logzio-dotnet/pull/8) main contributor @yellowblood is no longer works at logz. And he created "community" package. 

Can you provide support .NET Standard 1.3+?

**Comment by yellowblood** [comment]
I doubt they're monitoring this repo, you better ask their support directly (just go to https://app.logz.io/ and click the floating icon on the bottom right). They're very responsive.

**Comment by ranch78** [comment]
@sergiorykov - We are monitoring this repo - We will look into this and we will update

**Comment by idohalevi** [comment]
@sergiorykov 
Please check the new version

**Comment by idohalevi** [comment]
@ronaldbarendse 
Thank you! can you please check v1.0.1

**Comment by snakefoot** [comment]
@ronaldbarendse The support for Flush in Log4net required update of the Log4net-library (Together with support for NetCore).

Log4net Ver. 2.0.8 is over 1 year old. If you really like old nuget-packages, then just use the previous version, instead of the latest release.

**Comment by snakefoot** [comment]
@idohalevi To include support for NetStandard1.3, then this library need to change from using `WebClient` to `HttpClient`

**Comment by ronaldbarendse** [comment]
@snakefoot A valid point for upgrading log4net for the Flush support, but please don't upgrade library dependencies because they're old: you should actually target the lowest version your library works with: https://softwareengineering.stackexchange.com/questions/336279/policies-on-nuget-dependencies-versions-when-developing-a-library.

**Comment by idohalevi** [comment]
@ronaldbarendse 
I have no problem to downgrade Newtonsoft.Json, but I have to agree with @snakefoot on Log4Net version. I'm also open to hear if you have any other suggestion on how to solve this

**Comment by snakefoot** [comment]
Created #24 to resolve this
