### ISSUE TITLE
.NET Standard support in nuget package

### ISSUE THREAD

**Issue by bernard-chen** [logzio/logzio-dotnet#17]
I see in the commit history that the code support .NET Standard 2.0, but the Logzio.DotNet.NLog 0.21.0 nuget package contains only net45 and net46 assets. Where can I get a copy of the nuget package that includes .NET Standard support? Thanks!

**Comment by snakefoot** [comment]
When #16 has been merged.

**Comment by snakefoot** [comment]
When #16 has been merged. @idohalevi any progress there?

**Comment by idohalevi** [comment]
@snakefoot 
Yes I'll do it on Monday

**Comment by bernard-chen** [comment]
Thank you!


________________________________

**Comment by idohalevi** [comment]
done :)
