### ISSUE TITLE
SSL/TLS Error

### ISSUE THREAD

**Issue by spib** [logzio/logzio-dotnet#21]
Hi

We're seeing this error on a couple of our servers (running Windows 2008 R2 Server, appender version 1.0.1)

    System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
      at System.Net.HttpWebRequest.GetRequestStream
      at System.Net.HttpWebRequest.GetRequestStream
      at System.Net.WebClient.UploadBits
      at System.Net.WebClient.UploadDataInternal
      at System.Net.WebClient.UploadDataInternal
      at System.Net.WebClient.UploadString
      at Logzio.DotNet.Core.Shipping.BulkSender.Send

Any suggestions about how to fix this?

**Comment by snakefoot** [comment]
Might also be relevant: https://support.microsoft.com/help/4458166/applications-that-rely-on-tls-1-2-strong-encryption-experience-connect failures after a Windows upgrade.

**Comment by idohalevi** [comment]
@spib 
Are you using nlog or log4net ? also, what kind of version do you use?

**Comment by snakefoot** [comment]
@idohalevi I'm guessing it is the Log4net-Appender ver. 1.0.1

**Comment by snakefoot** [comment]
@spib You could also try and add this line at the beginning of your application:

`System.Net.ServicePointManager.SecurityProtocol |= System.Net.SecurityProtocolType.Tls12;`

This is a global change and will affect all connections in your application. But read the microsoft-support-article first (previous comment).

**Comment by spib** [comment]
Thanks, I was able to resolve it by setting the `SchUseStrongCrypto` registry key
