### ISSUE TITLE
Events logged to logz.io have fields prefixed by "LogData"

### ISSUE THREAD

**Issue by bernard-chen** [logzio/logzio-dotnet#25]
I'm using the Logzio.DotNet.NLog NuGet package with version 1.0.1. When data is sent to logz.io, the various entries are all prefixed with "LogData" (e.g., LogData.Message instead of just Message). I believe this is because we were serializing the LogEvent to send to logz.io, rather than LogEvent.LogData. This appears to be fixed in the commit 1d4fc7 (https://github.com/logzio/logzio-dotnet/commit/1d4fc7dcbe91d64271d8be7a49d4c92a8fb0cd98). Do we know when there will be a NuGet release that includes this fix?

**Comment by snakefoot** [comment]
@bernard-chen Think estimate is some time next week: https://github.com/logzio/logzio-dotnet/pull/19#issuecomment-416468211

**Comment by idohalevi** [comment]
@bernard-chen 
Hi, just like @snakefoot said we will release it by at the beginning of the week

**Comment by snakefoot** [comment]
I'm sorry about this. But need to make a ver 1.0.3 where the Json dependency is fixed (again).



Sent from my Samsung device


-------- Original message --------
