### ISSUE TITLE
Using log4net appender in a web application

### ISSUE THREAD

**Issue by ShyAlon** [logzio/logzio-dotnet#29]
We are using log4net in our ASP.NET application.
After installing the appender the web.config was updated to include:

```
<log4net debug="true">
    <appender name="LogzioAppender" type="Logzio.DotNet.Log4net.LogzioAppender, Logzio.DotNet.Log4net">
      <token>ourToken</token>
      <type>log4net</type>
      <listenerUrl>https://listener.logz.io:8071</listenerUrl>
      <bufferSize>10</bufferSize>
      <bufferTimeout>00:00:05</bufferTimeout>
      <retriesMaxAttempts>10</retriesMaxAttempts>
      <retriesInterval>00:00:01.01</retriesInterval>
    </appender>
    <appender name="ColoredConsoleAppender" type="log4net.Appender.ColoredConsoleAppender">
      ...
    </appender>
    <root>
      <level value="DEBUG" />
      <appender-ref ref="LogzioAppender" />
      <appender-ref ref="ColoredConsoleAppender" />
    </root>
  </log4net>
```

The logs are not getting shipped but there is no error message or any indication to what's wrong.

**Comment by idohalevi** [comment]
@ShyAlon 
Hi, I never encounter that, are you sure the app didn't close before the bufferTimeout reached? can you try send one message and then close/flush the logger and see if it reached Logz.io?

**Comment by ShyAlon** [comment]
Hi Ido
Turns out that the sample application works (for some reason it had really high latency)
Now it's not working on our main app but I can't expose the code.
Thanks for helping.

**Comment by idohalevi** [comment]
@ShyAlon I think it takes for kibana up to 30sec to update. If there is something else I could do to help let me know

**Comment by yellowblood** [comment]
@ShyAlon You might wanna enable debug mode in log4net, and enable the debug flag in the logzio appender (`<debug>true</debug>`).
