### ISSUE TITLE
Adding context properties programmatically

### ISSUE THREAD

**Issue by nivnahmias** [logzio/logzio-dotnet#31]
We noticed since updating to a more recent of logzio-dotnet our variables aren't being sent to logzio.
I saw that on #22 we are supposed to manually add them through context properties.

How do we add the context properties programmatically? I couldn't find an example for that in the docs.

For example, how do we add an "environment" key to all of our logs?

(we don't use a config file for initialising our NLog)

**Comment by nivnahmias** [comment]
I ended up going with something like this `config.Variables.Keys.ToList().ForEach(k => logzioTarget.ContextProperties.Add(new TargetPropertyWithContext(k, Layout.FromString($"${{var:{k}}}"))));`

**Comment by idohalevi** [comment]
@nivnahmias 
Sorry got the late response. I'm glad you worked it out :)
