### ISSUE TITLE
Shipper contains race-conditions and async/thread issues

### ISSUE THREAD

**Issue by ronaldbarendse** [logzio/logzio-dotnet#34]
We're having major troubles with web applications randomly becoming unresponsive (timing out and returning 503 errors), because the thead pool is exhausted (with hundreds of waiting threads). After looking at all components, it seems the generic `Shipper` used in `Logzio.DotNet.Log4Net` contains some race-conditions that could cause threads to become blocked and starts new threads using [`Task.Run()`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run?view=netframework-4.8#System_Threading_Tasks_Task_Run_System_Func_System_Threading_Tasks_Task__)...

So just to sum up my observations:

The `_timeoutReached` field is modified by multiple threads, but isn't marked [`volatile`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile), which could result in unpredictable results:
https://github.com/logzio/logzio-dotnet/blob/5e3c4de567965e82b5c49969fdd21d2bdad9d590/src/Core/Shipping/Shipper.cs#L25

The delay task contains no locking (race-condition) and doesn't set `ConfigureAwait(false)`:
https://github.com/logzio/logzio-dotnet/blob/5e3c4de567965e82b5c49969fdd21d2bdad9d590/src/Core/Shipping/Shipper.cs#L40-L41

Sending logs is done in a `Task.Run()`, which queues the specified work to run on the thread pool and returns a proxy for the task (see linked documentation above) and also doesn't set `ConfigureAwait(false)`:
https://github.com/logzio/logzio-dotnet/blob/5e3c4de567965e82b5c49969fdd21d2bdad9d590/src/Core/Shipping/Shipper.cs#L95

**Comment by idohalevi** [comment]
@ronaldbarendse Thank you for the detailed issue. 
I will get to this as fast as I can. If you have a local fix it will be faster to submit a PR, if not I will have some updates in the next couple of days.

**Comment by idohalevi** [comment]
@ronaldbarendse
I'm not sure volatile will help. I'm trying to set up an environment to reproduce this issue and will update when I can.
Please let me know if you find that the root of your problem it not from this sender

**Comment by idohalevi** [comment]
@ronaldbarendse I couldn't reproduce this issue. Any suggestion on how to do so?

**Comment by yellowblood** [comment]
None of the shipper tasks can be awaited by the calling thread so I fail to see how `ConfigureAwait(false)` is relevant here. The familiar UI/ASP async deadlock cannot happen in this case, unless I'm missing something.

The multiple writing calls to the `_timeoutReached` field aren't ideal, I don't think `volatile` is the solution, should probably just change the logic to work in a different way.

**Comment by ronaldbarendse** [comment]
We haven't found the root issue yet, so most of this is based on reviewing the code (hence the 'seems' and 'coulds').

Adding the `ConfigureAwait(false)` in library code is a good practice, so even if it's not relevant, I would still recommend this (see https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f).

**Comment by yellowblood** [comment]
@ronaldbarendse I'm familiar with this article - but it's not relevant here, since the code doesn't expose any asynchronous method to the user (to you). Meaning, you cannot `await` or `.Result` anything in this library when you're using it. This is why `ConfigureAwait(false)` is irrelevant - the library doesn't use the application thread at all.

**Comment by snakefoot** [comment]
#39 resolves the "issues" with "missing" `ConfigureAwait(false)`. But since all async-code was executed within the context of `Task.Run` then it doesn't matter. But now people with async-OCD can get their sleep again.
