### ISSUE TITLE
NDC count always 0. 

### ISSUE THREAD

**Issue by rolfwessels** [logzio/logzio-dotnet#36]
Hi,

I'm wondering how I can setup NDC reporting for log4net.

Here is my setup 

```csharp
  var appender = new LogzioAppender();
  appender.AddToken(_logSettings.LogzioToken);
  appender.AddType("log4net");
  appender.AddListenerUrl("xxxxxxxxx");
  appender.AddBufferSize(5);
  appender.AddBufferTimeout(TimeSpan.FromMilliseconds(500));
  appender.AddRetriesMaxAttempts(3);
  
  appender.AddCustomField(new LogzioAppenderCustomField {Key = "api", Value = _logSettings.UserName});
  appender.AddCustomField(new LogzioAppenderCustomField {Key = "environment", Value = _logSettings.Environment});
  appender.AddCustomField(new LogzioAppenderCustomField { Key = "ndcinc", Value = "%property{NDC}" });
  appender.AddCustomField(new LogzioAppenderCustomField { Key = "ndc1", Value = "Smile" });
  appender.AddDebug(false);
  appender.ActivateOptions();
  hierarchy.Root.AddAppender(appender);
```
```xml
<PackageReference Include="Log2Slack.Log4Net" Version="0.2.0" />
```

Looking on logzio I get the following.
![image](https://user-images.githubusercontent.com/643179/67466899-22985e80-f648-11e9-9fde-dca512085cf2.png)

It does seem like the intent is there for ndc but mine is always logged as ` ndc.count= 0`

I have tried setting custom properties just to try but it does not seem to work.

Any ideas? 

Thanks

**Comment by yellowblood** [comment]
NDC moved to be part of the ThreadContext - 
https://logging.apache.org/log4net/log4net-1.2.13/release/sdk/log4net.NDC.html

You should be able to implement this by inheriting `LogzioAppender`, overriding `ExtendValues`  and adding whatever you want from the `ThreadContext` object.

The `CustomFields` are usually static (environment as the best use case).
