### ISSUE TITLE
Not send message NLog

### ISSUE THREAD

**Issue by TemoxaGreenMoney** [logzio/logzio-dotnet#37]
Hi, i'am install and setup our package with NLog 4.6.8/NetFramework 7.2.1 and create logger manager class for send message on our platform logz.io

`
public class ManagerLog
    {
        private static Logger Logger = LogManager.GetCurrentClassLogger();

        public ManagerLog()
        {
            var config = new LoggingConfiguration();
            var logzioTarget = new LogzioTarget
            {
                Token = "TOKEN1234",
                ListenerUrl = "https://listener.logz.io:8071",
                BufferSize = 1,
                LogzioType = "nlog",
                Name = "LogzioTarget"
            };
            config.AddTarget("Logzio", logzioTarget);
            config.AddRule(LogLevel.Debug, LogLevel.Fatal, "Logzio", "*");
            LogManager.Configuration = config;
        }

        public void LogInfo(string message)
        {
            Logger.Info(message);
        }

        public void LogWarn(string message)
        {
            Logger.Warn(message);
        }

        public void LogError(string message, Exception e)
        {
            Logger.Error(e, message);
        }
    }`

Now when invoke method ManagerLog.LogInfo("Test") do nothings! Exceptions not do(

Help me please

**Comment by snakefoot** [comment]
[Remember to flush](https://github.com/nlog/nlog/wiki/Tutorial#5-remember-to-flush)
