### ISSUE TITLE
Recommendations for Serilog

### ISSUE THREAD

**Issue by danielwertheim** [logzio/logzio-dotnet#40]
What are the recommendations of how-to ship your logs to logz.io if you are using Serilog running on Azure appservices etc?

**Comment by idohalevi** [comment]
Depending on the logs you're trying to send to Logz.io you have two options:

1) According to [this](https://docs.logz.io/shipping/log-sources/azure-diagnostic-logs.html), you can use Logz.io **_Diagnostic Settings_** [integration](https://docs.logz.io/shipping/log-sources/azure-diagnostic-logs.html)
2) Use our community [integrations](https://docs.logz.io/shipping/)
