### ISSUE TITLE
Logzio.DotNet.Log4net package won't install. Is the log4net appender supported to run in .net core applications?

### ISSUE THREAD

**Issue by gitfortee** [logzio/logzio-dotnet#5]
Package Logzio.DotNet.Log4net 0.20.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Logzio.DotNet.Log4net 0.20.0 supports:
  - net45 (.NETFramework,Version=v4.5)
  - net46 (.NETFramework,Version=v4.6)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
Package restore failed. Rolling back package changes for 'EmailService.Console'.

**Comment by yellowblood** [comment]
Hi,

I'll add support for .NET core as soon as I can. In the meanwhile, you can checkout the repo and compile it on your environment.

**Comment by gitfortee** [comment]
Ok. thanks for the response.

**Comment by idohalevi** [comment]
@snakefoot 
On it, I'll close this when ready
