### ISSUE TITLE
Custom fields in CamelCase are sent to logz.io as camelCase

### ISSUE THREAD

**Issue by Ekhozie** [logzio/logzio-dotnet#59]
Hello,
I am using the library `Logzio.DotNet.Log4net` version `1.0.11` and I have a problem with custom fields.
When I use
```csharp
         appender.AddCustomField(new LogzioAppenderCustomField
            {
                Key = "EnvironmentName",
                Value = "Production"
            });
```
In logz.io I get the key `environmentName` instead of `EnvironmentName` whereas it's working with the serilog library `Serilog.Sinks.Http.LogzIo`
Thanks for your help.

**Comment by ShiranAvidov** [comment]
Hi,
Thanks for letting us know about this problem. I am working right now on a solution, it should not take long.
I will update you know when it will be published and how to use it.

**Comment by ShiranAvidov** [comment]
Hi,
You need to use the updated nuget package version 1.0.12. You can add jsonKeysCamelCase to your config or to your code (see examples under docs/log4net.md in this repo) and set it to true. That is it. You should see your keys in camel case.

**Comment by Ekhozie** [comment]
Hi,
It works, thank you very much 👍
