### ISSUE TITLE
Please document target properties

### ISSUE THREAD

**Issue by lukos** [logzio/logzio-dotnet#63]
You mention jsonKeysCamelCase and set it to false by default but without documentation, this is the opposite of what I would expect. I read this as "convert keys to camel case" in which case I expect it to be false if I want my properties left along, but this is the opposite of what is happening.

I am not sure how to read the property any other way so ideally it should be renamed or th elogic reversed but at least it should be documented that it means "false = convert to camel case" and "true = don't convert property names".

Thanks

**Comment by ShiranAvidov** [comment]
Hi lukos,
Thanks for your suggestion. I am updating the documentation. You should be able to see the update soon :)
